//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2053.0.
// 
namespace EfDatabaseXsdSupportNalog {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelParametrSupport {
        
        private string loginField;
        
        private string passwordField;
        
        private string discriptionField;
        
        private int idUserField;
        
        private int idMfuField;
        
        private int idMonitorField;
        
        private int idPrinterField;
        
        private int idSysBlockField;
        
        private int idTemplateField;
        
        private int idScannerField;
        
        private int idTelephonField;
        
        private int idAnalisysEpoField;
        
        private TemplateSupport1[] templateSupportField;
        
        private string step3ResponseSupportField;
        
        private string errorField;
        
        private int idCalendarVksField;
        
        private AksiokAddAndEdit aksiokAddAndEditField;
        
        public ModelParametrSupport() {
            this.idUserField = 0;
            this.idMfuField = 0;
            this.idMonitorField = 0;
            this.idPrinterField = 0;
            this.idSysBlockField = 0;
            this.idTemplateField = 0;
            this.idScannerField = 0;
            this.idTelephonField = 0;
            this.idAnalisysEpoField = 0;
            this.idCalendarVksField = 0;
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Discription {
            get {
                return this.discriptionField;
            }
            set {
                this.discriptionField = value;
            }
        }
        
        /// <remarks/>
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        public int IdMfu {
            get {
                return this.idMfuField;
            }
            set {
                this.idMfuField = value;
            }
        }
        
        /// <remarks/>
        public int IdMonitor {
            get {
                return this.idMonitorField;
            }
            set {
                this.idMonitorField = value;
            }
        }
        
        /// <remarks/>
        public int IdPrinter {
            get {
                return this.idPrinterField;
            }
            set {
                this.idPrinterField = value;
            }
        }
        
        /// <remarks/>
        public int IdSysBlock {
            get {
                return this.idSysBlockField;
            }
            set {
                this.idSysBlockField = value;
            }
        }
        
        /// <remarks/>
        public int IdTemplate {
            get {
                return this.idTemplateField;
            }
            set {
                this.idTemplateField = value;
            }
        }
        
        /// <remarks/>
        public int IdScanner {
            get {
                return this.idScannerField;
            }
            set {
                this.idScannerField = value;
            }
        }
        
        /// <remarks/>
        public int IdTelephon {
            get {
                return this.idTelephonField;
            }
            set {
                this.idTelephonField = value;
            }
        }
        
        /// <remarks/>
        public int IdAnalisysEpo {
            get {
                return this.idAnalisysEpoField;
            }
            set {
                this.idAnalisysEpoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TemplateSupport", IsNullable=true)]
        public TemplateSupport1[] TemplateSupport {
            get {
                return this.templateSupportField;
            }
            set {
                this.templateSupportField = value;
            }
        }
        
        /// <remarks/>
        public string Step3ResponseSupport {
            get {
                return this.step3ResponseSupportField;
            }
            set {
                this.step3ResponseSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public int IdCalendarVks {
            get {
                return this.idCalendarVksField;
            }
            set {
                this.idCalendarVksField = value;
            }
        }
        
        /// <remarks/>
        public AksiokAddAndEdit AksiokAddAndEdit {
            get {
                return this.aksiokAddAndEditField;
            }
            set {
                this.aksiokAddAndEditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("TemplateSupport", Namespace="", IsNullable=true)]
    public partial class TemplateSupport1 : TemplateSupport {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TemplateSupport {
        
        private string nameField;
        
        private string infoTemplateField;
        
        private string nameStepSupportField;
        
        private string helpParameterField;
        
        private string nameGuidParametrField;
        
        private string parametrField;
        
        private byte[] parameterStep3Field;
        
        private string typeParametrField;
        
        private string nameParametrTypeField;
        
        private string selectParametrField;
        
        private string templateParametrTypeField;
        
        private bool isImportantField;
        
        private bool isImportantFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InfoTemplate {
            get {
                return this.infoTemplateField;
            }
            set {
                this.infoTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameStepSupport {
            get {
                return this.nameStepSupportField;
            }
            set {
                this.nameStepSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HelpParameter {
            get {
                return this.helpParameterField;
            }
            set {
                this.helpParameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameGuidParametr {
            get {
                return this.nameGuidParametrField;
            }
            set {
                this.nameGuidParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parametr {
            get {
                return this.parametrField;
            }
            set {
                this.parametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] ParameterStep3 {
            get {
                return this.parameterStep3Field;
            }
            set {
                this.parameterStep3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeParametr {
            get {
                return this.typeParametrField;
            }
            set {
                this.typeParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameParametrType {
            get {
                return this.nameParametrTypeField;
            }
            set {
                this.nameParametrTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SelectParametr {
            get {
                return this.selectParametrField;
            }
            set {
                this.selectParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TemplateParametrType {
            get {
                return this.templateParametrTypeField;
            }
            set {
                this.templateParametrTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsImportant {
            get {
                return this.isImportantField;
            }
            set {
                this.isImportantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsImportantSpecified {
            get {
                return this.isImportantFieldSpecified;
            }
            set {
                this.isImportantFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AksiokAddAndEdit {
        
        private ParametersModel parametersModelField;
        
        private KitsEquipment kitsEquipmentField;
        
        private ParametersRequestAksiok parametersRequestAksiokField;
        
        private UploadFileAksiok uploadFileAksiokField;
        
        /// <remarks/>
        public ParametersModel ParametersModel {
            get {
                return this.parametersModelField;
            }
            set {
                this.parametersModelField = value;
            }
        }
        
        /// <remarks/>
        public KitsEquipment KitsEquipment {
            get {
                return this.kitsEquipmentField;
            }
            set {
                this.kitsEquipmentField = value;
            }
        }
        
        /// <remarks/>
        public ParametersRequestAksiok ParametersRequestAksiok {
            get {
                return this.parametersRequestAksiokField;
            }
            set {
                this.parametersRequestAksiokField = value;
            }
        }
        
        /// <remarks/>
        public UploadFileAksiok UploadFileAksiok {
            get {
                return this.uploadFileAksiokField;
            }
            set {
                this.uploadFileAksiokField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ParametersModel {
        
        private int idFullCategoriaField;
        
        private int idStateField;
        
        private int idStateStoField;
        
        private int idExpertiseField;
        
        private System.Nullable<System.DateTime> guaranteeField;
        
        private string modelRequestField;
        
        private string nameProducerField;
        
        private string nameModelField;
        
        private string serNumberField;
        
        private string inventoryNumField;
        
        private int codeErrorField;
        
        private string errorServerField;
        
        private int yearOfIssueField;
        
        private int exploitationStartYearField;
        
        private bool isKitField;
        
        private string loginUserField;
        
        private string passwordField;
        
        public ParametersModel() {
            this.idFullCategoriaField = 0;
            this.idStateField = 0;
            this.idStateStoField = 0;
            this.idExpertiseField = 0;
            this.codeErrorField = 0;
            this.isKitField = false;
        }
        
        /// <remarks/>
        public int IdFullCategoria {
            get {
                return this.idFullCategoriaField;
            }
            set {
                this.idFullCategoriaField = value;
            }
        }
        
        /// <remarks/>
        public int IdState {
            get {
                return this.idStateField;
            }
            set {
                this.idStateField = value;
            }
        }
        
        /// <remarks/>
        public int IdStateSto {
            get {
                return this.idStateStoField;
            }
            set {
                this.idStateStoField = value;
            }
        }
        
        /// <remarks/>
        public int IdExpertise {
            get {
                return this.idExpertiseField;
            }
            set {
                this.idExpertiseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Guarantee {
            get {
                return this.guaranteeField;
            }
            set {
                this.guaranteeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModelRequest {
            get {
                return this.modelRequestField;
            }
            set {
                this.modelRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameProducer {
            get {
                return this.nameProducerField;
            }
            set {
                this.nameProducerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameModel {
            get {
                return this.nameModelField;
            }
            set {
                this.nameModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerNumber {
            get {
                return this.serNumberField;
            }
            set {
                this.serNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventoryNum {
            get {
                return this.inventoryNumField;
            }
            set {
                this.inventoryNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int CodeError {
            get {
                return this.codeErrorField;
            }
            set {
                this.codeErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorServer {
            get {
                return this.errorServerField;
            }
            set {
                this.errorServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int YearOfIssue {
            get {
                return this.yearOfIssueField;
            }
            set {
                this.yearOfIssueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ExploitationStartYear {
            get {
                return this.exploitationStartYearField;
            }
            set {
                this.exploitationStartYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsKit {
            get {
                return this.isKitField;
            }
            set {
                this.isKitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LoginUser {
            get {
                return this.loginUserField;
            }
            set {
                this.loginUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class KitsEquipment {
        
        private KitsEquipmentServer[] kitsEquipmentServerField;
        
        private string inventoryNumField;
        
        private string errorServerField;
        
        private bool isCheckedKitsField;
        
        private bool isNotCheckedKitsField;
        
        public KitsEquipment() {
            this.isCheckedKitsField = false;
            this.isNotCheckedKitsField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KitsEquipmentServer")]
        public KitsEquipmentServer[] KitsEquipmentServer {
            get {
                return this.kitsEquipmentServerField;
            }
            set {
                this.kitsEquipmentServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventoryNum {
            get {
                return this.inventoryNumField;
            }
            set {
                this.inventoryNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorServer {
            get {
                return this.errorServerField;
            }
            set {
                this.errorServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsCheckedKits {
            get {
                return this.isCheckedKitsField;
            }
            set {
                this.isCheckedKitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsNotCheckedKits {
            get {
                return this.isNotCheckedKitsField;
            }
            set {
                this.isNotCheckedKitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class KitsEquipmentServer {
        
        private int idField;
        
        private string serialNumberField;
        
        private string inventoryNumberField;
        
        private bool isKitField;
        
        private bool isKitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventoryNumber {
            get {
                return this.inventoryNumberField;
            }
            set {
                this.inventoryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsKit {
            get {
                return this.isKitField;
            }
            set {
                this.isKitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsKitSpecified {
            get {
                return this.isKitFieldSpecified;
            }
            set {
                this.isKitFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ParametersRequestAksiok {
        
        private FileAkt fileAktField;
        
        private FileExpertise fileExpertiseField;
        
        private int idTypeField;
        
        private int idProducerField;
        
        private int idModelField;
        
        private int idStateField;
        
        private int idStateStoField;
        
        private int idExpertiseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FileAkt FileAkt {
            get {
                return this.fileAktField;
            }
            set {
                this.fileAktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FileExpertise FileExpertise {
            get {
                return this.fileExpertiseField;
            }
            set {
                this.fileExpertiseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdProducer {
            get {
                return this.idProducerField;
            }
            set {
                this.idProducerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdModel {
            get {
                return this.idModelField;
            }
            set {
                this.idModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdState {
            get {
                return this.idStateField;
            }
            set {
                this.idStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdStateSto {
            get {
                return this.idStateStoField;
            }
            set {
                this.idStateStoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdExpertise {
            get {
                return this.idExpertiseField;
            }
            set {
                this.idExpertiseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class FileAkt {
        
        private string nameFileField;
        
        private byte[] fileField;
        
        private string typeFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeFile {
            get {
                return this.typeFileField;
            }
            set {
                this.typeFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class FileExpertise {
        
        private string nameFileField;
        
        private byte[] fileField;
        
        private string typeFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeFile {
            get {
                return this.typeFileField;
            }
            set {
                this.typeFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UploadFileAksiok {
        
        private string nameFileField;
        
        private byte[] fileField;
        
        private string typeFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeFile {
            get {
                return this.typeFileField;
            }
            set {
                this.typeFileField = value;
            }
        }
    }
}
