//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 
namespace EfDatabaseXsdSupportNalog {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelParametrSupport {
        
        private string loginField;
        
        private string passwordField;
        
        private string discriptionField;
        
        private int idUserField;
        
        private int idMfuField;
        
        private int idMonitorField;
        
        private int idPrinterField;
        
        private int idSysBlockField;
        
        private int idTemplateField;
        
        private int idScannerField;
        
        private TemplateSupport[] templateSupportField;
        
        private string step3ResponseSupportField;
        
        public ModelParametrSupport() {
            this.idUserField = 0;
            this.idMfuField = 0;
            this.idMonitorField = 0;
            this.idPrinterField = 0;
            this.idSysBlockField = 0;
            this.idTemplateField = 0;
            this.idScannerField = 0;
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Discription {
            get {
                return this.discriptionField;
            }
            set {
                this.discriptionField = value;
            }
        }
        
        /// <remarks/>
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        public int IdMfu {
            get {
                return this.idMfuField;
            }
            set {
                this.idMfuField = value;
            }
        }
        
        /// <remarks/>
        public int IdMonitor {
            get {
                return this.idMonitorField;
            }
            set {
                this.idMonitorField = value;
            }
        }
        
        /// <remarks/>
        public int IdPrinter {
            get {
                return this.idPrinterField;
            }
            set {
                this.idPrinterField = value;
            }
        }
        
        /// <remarks/>
        public int IdSysBlock {
            get {
                return this.idSysBlockField;
            }
            set {
                this.idSysBlockField = value;
            }
        }
        
        /// <remarks/>
        public int IdTemplate {
            get {
                return this.idTemplateField;
            }
            set {
                this.idTemplateField = value;
            }
        }
        
        /// <remarks/>
        public int IdScanner {
            get {
                return this.idScannerField;
            }
            set {
                this.idScannerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TemplateSupport", IsNullable=true)]
        public TemplateSupport[] TemplateSupport {
            get {
                return this.templateSupportField;
            }
            set {
                this.templateSupportField = value;
            }
        }
        
        /// <remarks/>
        public string Step3ResponseSupport {
            get {
                return this.step3ResponseSupportField;
            }
            set {
                this.step3ResponseSupportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class TemplateSupport {
        
        private string nameField;
        
        private string infoTemplateField;
        
        private string nameStepSupportField;
        
        private string helpParameterField;
        
        private string nameGuidParametrField;
        
        private string parametrField;
        
        private string typeParametrField;
        
        private string nameParametrTypeField;
        
        private string selectParametrField;
        
        private string templateParametrTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InfoTemplate {
            get {
                return this.infoTemplateField;
            }
            set {
                this.infoTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameStepSupport {
            get {
                return this.nameStepSupportField;
            }
            set {
                this.nameStepSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HelpParameter {
            get {
                return this.helpParameterField;
            }
            set {
                this.helpParameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameGuidParametr {
            get {
                return this.nameGuidParametrField;
            }
            set {
                this.nameGuidParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parametr {
            get {
                return this.parametrField;
            }
            set {
                this.parametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeParametr {
            get {
                return this.typeParametrField;
            }
            set {
                this.typeParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameParametrType {
            get {
                return this.nameParametrTypeField;
            }
            set {
                this.nameParametrTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SelectParametr {
            get {
                return this.selectParametrField;
            }
            set {
                this.selectParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TemplateParametrType {
            get {
                return this.templateParametrTypeField;
            }
            set {
                this.templateParametrTypeField = value;
            }
        }
    }
}
