//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 
namespace EfDatabase.ModelAksiok.Aksiok {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AksiokAddAndEdit {
        
        private ParametersModel parametersModelField;
        
        /// <remarks/>
        public ParametersModel ParametersModel {
            get {
                return this.parametersModelField;
            }
            set {
                this.parametersModelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ParametersModel {
        
        private System.Nullable<int> idFullCategoriaField;
        
        private string modelRequestField;
        
        private string serNumberField;
        
        private string inventoryNumField;
        
        private int codeErrorField;
        
        private string errorServerField;
        
        public ParametersModel() {
            this.codeErrorField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdFullCategoria {
            get {
                return this.idFullCategoriaField;
            }
            set {
                this.idFullCategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModelRequest {
            get {
                return this.modelRequestField;
            }
            set {
                this.modelRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerNumber {
            get {
                return this.serNumberField;
            }
            set {
                this.serNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventoryNum {
            get {
                return this.inventoryNumField;
            }
            set {
                this.inventoryNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int CodeError {
            get {
                return this.codeErrorField;
            }
            set {
                this.codeErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorServer {
            get {
                return this.errorServerField;
            }
            set {
                this.errorServerField = value;
            }
        }
    }
}
