//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 
namespace EfDatabase.ModelAksiok.Aksiok {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelAksiok {
        
        private ModelDocumentType[] modelDocumentTypeField;
        
        private ModelDocument[] modelDocumentField;
        
        private EpoDocument epoDocumentField;
        
        private ValueCharacteristicJson valueCharacteristicJsonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModelDocumentType", IsNullable=true)]
        public ModelDocumentType[] ModelDocumentType {
            get {
                return this.modelDocumentTypeField;
            }
            set {
                this.modelDocumentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModelDocument", IsNullable=true)]
        public ModelDocument[] ModelDocument {
            get {
                return this.modelDocumentField;
            }
            set {
                this.modelDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EpoDocument EpoDocument {
            get {
                return this.epoDocumentField;
            }
            set {
                this.epoDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ValueCharacteristicJson ValueCharacteristicJson {
            get {
                return this.valueCharacteristicJsonField;
            }
            set {
                this.valueCharacteristicJsonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ModelDocumentType {
        
        private int idField;
        
        private string sounField;
        
        private int documentTypeField;
        
        private string kindEquipmentNameField;
        
        private string categoriesTruNameField;
        
        private string numberField;
        
        private string authorField;
        
        private bool canDeleteField;
        
        private string agencyNameField;
        
        private System.DateTime createDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Soun {
            get {
                return this.sounField;
            }
            set {
                this.sounField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KindEquipmentName {
            get {
                return this.kindEquipmentNameField;
            }
            set {
                this.kindEquipmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CategoriesTruName {
            get {
                return this.categoriesTruNameField;
            }
            set {
                this.categoriesTruNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CanDelete {
            get {
                return this.canDeleteField;
            }
            set {
                this.canDeleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AgencyName {
            get {
                return this.agencyNameField;
            }
            set {
                this.agencyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ModelDocument {
        
        private System.Nullable<int> fileIdField;
        
        private System.Nullable<int> expertiseFileIdField;
        
        private int idField;
        
        private string equipmentTypeField;
        
        private string producerField;
        
        private string equipmentModelField;
        
        private string serialNumberField;
        
        private string inventoryNumberField;
        
        private int equipmentStateField;
        
        private int equipmentStateStoField;
        
        private bool isKitField;
        
        private int expertiseStatusField;
        
        private bool isTruInSettingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ExpertiseFileId {
            get {
                return this.expertiseFileIdField;
            }
            set {
                this.expertiseFileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EquipmentType {
            get {
                return this.equipmentTypeField;
            }
            set {
                this.equipmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Producer {
            get {
                return this.producerField;
            }
            set {
                this.producerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EquipmentModel {
            get {
                return this.equipmentModelField;
            }
            set {
                this.equipmentModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventoryNumber {
            get {
                return this.inventoryNumberField;
            }
            set {
                this.inventoryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int EquipmentState {
            get {
                return this.equipmentStateField;
            }
            set {
                this.equipmentStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int EquipmentStateSto {
            get {
                return this.equipmentStateStoField;
            }
            set {
                this.equipmentStateStoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsKit {
            get {
                return this.isKitField;
            }
            set {
                this.isKitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ExpertiseStatus {
            get {
                return this.expertiseStatusField;
            }
            set {
                this.expertiseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsTruInSettings {
            get {
                return this.isTruInSettingsField;
            }
            set {
                this.isTruInSettingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class EpoDocument {
        
        private EquipmentType equipmentTypeField;
        
        private Producer producerField;
        
        private EquipmentModel equipmentModelField;
        
        private System.Nullable<System.DateTime> actDateField;
        
        private System.Nullable<System.DateTime> dateOfStatementField;
        
        private File fileField;
        
        private ExpertiseFile expertiseFileField;
        
        private System.Nullable<int> exploitationStartYearField;
        
        private DeliveryContract deliveryContractField;
        
        private ContractOnSto contractOnStoField;
        
        private System.Nullable<System.DateTime> guaranteeField;
        
        private System.Nullable<int> boardsNumberField;
        
        private System.Nullable<int> freeBoardsNumberField;
        
        private System.Nullable<int> internalAnalogNumberField;
        
        private System.Nullable<int> internalDigitNumberField;
        
        private System.Nullable<int> adminsCountField;
        
        private int idField;
        
        private int epoDocument1Field;
        
        private string computerNameField;
        
        private string serialNumberField;
        
        private string identifierField;
        
        private string inventoryNumberField;
        
        private bool isKitField;
        
        private int equipmentStateStoField;
        
        private int equipmentStateField;
        
        private string actNumberField;
        
        private int expertiseStatusField;
        
        private string serviceNumberField;
        
        private string individualServiceNumberField;
        
        private string notOnBalanceField;
        
        private int yearOfIssueField;
        
        private string commentField;
        
        private string serviceStatusField;
        
        private string osActualVersionField;
        
        private string actualOsVersionField;
        
        private string appointmentField;
        
        private string typeOfUseField;
        
        private string divisionField;
        
        private string modelInDeliveryAccordanceField;
        
        private string buildingField;
        
        private string floorLocationField;
        
        private string roomLocationField;
        
        private string psVersionField;
        
        private string ipAddressField;
        
        private string typeOfAnalogConnectionField;
        
        private string typeOfDigitConnectionField;
        
        private string keyNumberField;
        
        private bool requiresReplacementField;
        
        /// <remarks/>
        public EquipmentType EquipmentType {
            get {
                return this.equipmentTypeField;
            }
            set {
                this.equipmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public Producer Producer {
            get {
                return this.producerField;
            }
            set {
                this.producerField = value;
            }
        }
        
        /// <remarks/>
        public EquipmentModel EquipmentModel {
            get {
                return this.equipmentModelField;
            }
            set {
                this.equipmentModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ActDate {
            get {
                return this.actDateField;
            }
            set {
                this.actDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateOfStatement {
            get {
                return this.dateOfStatementField;
            }
            set {
                this.dateOfStatementField = value;
            }
        }
        
        /// <remarks/>
        public File File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public ExpertiseFile ExpertiseFile {
            get {
                return this.expertiseFileField;
            }
            set {
                this.expertiseFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ExploitationStartYear {
            get {
                return this.exploitationStartYearField;
            }
            set {
                this.exploitationStartYearField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryContract DeliveryContract {
            get {
                return this.deliveryContractField;
            }
            set {
                this.deliveryContractField = value;
            }
        }
        
        /// <remarks/>
        public ContractOnSto ContractOnSto {
            get {
                return this.contractOnStoField;
            }
            set {
                this.contractOnStoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Guarantee {
            get {
                return this.guaranteeField;
            }
            set {
                this.guaranteeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BoardsNumber {
            get {
                return this.boardsNumberField;
            }
            set {
                this.boardsNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FreeBoardsNumber {
            get {
                return this.freeBoardsNumberField;
            }
            set {
                this.freeBoardsNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> InternalAnalogNumber {
            get {
                return this.internalAnalogNumberField;
            }
            set {
                this.internalAnalogNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> InternalDigitNumber {
            get {
                return this.internalDigitNumberField;
            }
            set {
                this.internalDigitNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AdminsCount {
            get {
                return this.adminsCountField;
            }
            set {
                this.adminsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("EpoDocument")]
        public int EpoDocument1 {
            get {
                return this.epoDocument1Field;
            }
            set {
                this.epoDocument1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComputerName {
            get {
                return this.computerNameField;
            }
            set {
                this.computerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventoryNumber {
            get {
                return this.inventoryNumberField;
            }
            set {
                this.inventoryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsKit {
            get {
                return this.isKitField;
            }
            set {
                this.isKitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int EquipmentStateSto {
            get {
                return this.equipmentStateStoField;
            }
            set {
                this.equipmentStateStoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int EquipmentState {
            get {
                return this.equipmentStateField;
            }
            set {
                this.equipmentStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ActNumber {
            get {
                return this.actNumberField;
            }
            set {
                this.actNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ExpertiseStatus {
            get {
                return this.expertiseStatusField;
            }
            set {
                this.expertiseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IndividualServiceNumber {
            get {
                return this.individualServiceNumberField;
            }
            set {
                this.individualServiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NotOnBalance {
            get {
                return this.notOnBalanceField;
            }
            set {
                this.notOnBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int YearOfIssue {
            get {
                return this.yearOfIssueField;
            }
            set {
                this.yearOfIssueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OsActualVersion {
            get {
                return this.osActualVersionField;
            }
            set {
                this.osActualVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ActualOsVersion {
            get {
                return this.actualOsVersionField;
            }
            set {
                this.actualOsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Appointment {
            get {
                return this.appointmentField;
            }
            set {
                this.appointmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeOfUse {
            get {
                return this.typeOfUseField;
            }
            set {
                this.typeOfUseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModelInDeliveryAccordance {
            get {
                return this.modelInDeliveryAccordanceField;
            }
            set {
                this.modelInDeliveryAccordanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FloorLocation {
            get {
                return this.floorLocationField;
            }
            set {
                this.floorLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoomLocation {
            get {
                return this.roomLocationField;
            }
            set {
                this.roomLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PsVersion {
            get {
                return this.psVersionField;
            }
            set {
                this.psVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeOfAnalogConnection {
            get {
                return this.typeOfAnalogConnectionField;
            }
            set {
                this.typeOfAnalogConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeOfDigitConnection {
            get {
                return this.typeOfDigitConnectionField;
            }
            set {
                this.typeOfDigitConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KeyNumber {
            get {
                return this.keyNumberField;
            }
            set {
                this.keyNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool RequiresReplacement {
            get {
                return this.requiresReplacementField;
            }
            set {
                this.requiresReplacementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class EquipmentType {
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private bool endDateFieldSpecified;
        
        private Producer producerField;
        
        private int idField;
        
        private string codeField;
        
        private string nameField;
        
        private string commentField;
        
        private System.DateTime startDate1Field;
        
        private bool startDate1FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Producer Producer {
            get {
                return this.producerField;
            }
            set {
                this.producerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("StartDate")]
        public System.DateTime StartDate1 {
            get {
                return this.startDate1Field;
            }
            set {
                this.startDate1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDate1Specified {
            get {
                return this.startDate1FieldSpecified;
            }
            set {
                this.startDate1FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Producer {
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private bool endDateFieldSpecified;
        
        private EquipmentModel equipmentModelField;
        
        private int idField;
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public EquipmentModel EquipmentModel {
            get {
                return this.equipmentModelField;
            }
            set {
                this.equipmentModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class EquipmentModel {
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private bool endDateFieldSpecified;
        
        private int idField;
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class File {
        
        private System.Nullable<int> idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ExpertiseFile {
        
        private System.Nullable<int> idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DeliveryContract {
        
        private int idField;
        
        private string numberField;
        
        private string nameField;
        
        private System.DateTime contractDateField;
        
        private string executorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ContractDate {
            get {
                return this.contractDateField;
            }
            set {
                this.contractDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Executor {
            get {
                return this.executorField;
            }
            set {
                this.executorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ContractOnSto {
        
        private int idField;
        
        private string numberField;
        
        private string nameField;
        
        private System.DateTime contractDateField;
        
        private string executorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ContractDate {
            get {
                return this.contractDateField;
            }
            set {
                this.contractDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Executor {
            get {
                return this.executorField;
            }
            set {
                this.executorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ValueCharacteristicJson {
        
        private System.Nullable<int> cpuCountField;
        
        private System.Nullable<int> coreCountField;
        
        private System.Nullable<int> hddCountField;
        
        private System.Nullable<int> boardsNumberField;
        
        private System.Nullable<int> freeBoardsNumberField;
        
        private System.Nullable<int> internalAnalogNumberField;
        
        private System.Nullable<int> internalDigitNumberField;
        
        private System.Nullable<int> adminsCountField;
        
        private System.Nullable<System.DateTime> guaranteeField;
        
        private System.Nullable<int> hddSizeField;
        
        private System.Nullable<int> networkAdapterSpeedField;
        
        private System.Nullable<int> totalDiskSpaceGbField;
        
        private System.Nullable<int> ramSizeField;
        
        private System.Nullable<int> cpuFrequencyMhzField;
        
        private int idField;
        
        private string notOnBalanceField;
        
        private bool requiresReplacementField;
        
        private string appointmentField;
        
        private string virtualizationEnvironmentField;
        
        private string buildingField;
        
        private string floorLocationField;
        
        private string roomLocationField;
        
        private string roomField;
        
        private string divisionField;
        
        private string actualOsVersionField;
        
        private string osActualVersionField;
        
        private string zagsNameField;
        
        private string zagsAddressField;
        
        private string typeOfUseField;
        
        private string modelInDeliveryAccordanceField;
        
        private string transferContractNumberField;
        
        private string psVersionField;
        
        private string netBiosNameField;
        
        private string ipAddressField;
        
        private string additionalIPsField;
        
        private string cpuTypeField;
        
        private string ramTypeField;
        
        private string cdOrDvdField;
        
        private string fddField;
        
        private string raidField;
        
        private string hddTypeField;
        
        private string networkAdapterField;
        
        private string connectedPcInventoryNumberField;
        
        private string connectedUpsInventoryNumberField;
        
        private string displayInventoryNumberField;
        
        private string displayServiceNumberField;
        
        private string displayBrandField;
        
        private string displayTypeField;
        
        private string displaySizeField;
        
        private string displayMaxResolutionField;
        
        private string typeOfAnalogConnectionField;
        
        private string typeOfDigitConnectionField;
        
        private string keyNumberField;
        
        private string streamerBrandField;
        
        private string streamerCartridgeMarkField;
        
        private string operatingSystemField;
        
        private string servicePackField;
        
        private string officeSuiteField;
        
        private string fioField;
        
        private string responsiblePersonField;
        
        private string descriptionField;
        
        private string macAddressField;
        
        private string yearOfIssueField;
        
        private string computerNameField;
        
        private string inventoryNumberField;
        
        private string commentsField;
        
        private string supplyContractField;
        
        private string contractStoField;
        
        private string serviceNumberField;
        
        private string serialNumberField;
        
        private string mailServerField;
        
        private string firewallMailServerField;
        
        private string firewallForVksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CpuCount {
            get {
                return this.cpuCountField;
            }
            set {
                this.cpuCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CoreCount {
            get {
                return this.coreCountField;
            }
            set {
                this.coreCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> HddCount {
            get {
                return this.hddCountField;
            }
            set {
                this.hddCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BoardsNumber {
            get {
                return this.boardsNumberField;
            }
            set {
                this.boardsNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FreeBoardsNumber {
            get {
                return this.freeBoardsNumberField;
            }
            set {
                this.freeBoardsNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> InternalAnalogNumber {
            get {
                return this.internalAnalogNumberField;
            }
            set {
                this.internalAnalogNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> InternalDigitNumber {
            get {
                return this.internalDigitNumberField;
            }
            set {
                this.internalDigitNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AdminsCount {
            get {
                return this.adminsCountField;
            }
            set {
                this.adminsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Guarantee {
            get {
                return this.guaranteeField;
            }
            set {
                this.guaranteeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> HddSize {
            get {
                return this.hddSizeField;
            }
            set {
                this.hddSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NetworkAdapterSpeed {
            get {
                return this.networkAdapterSpeedField;
            }
            set {
                this.networkAdapterSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TotalDiskSpaceGb {
            get {
                return this.totalDiskSpaceGbField;
            }
            set {
                this.totalDiskSpaceGbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RamSize {
            get {
                return this.ramSizeField;
            }
            set {
                this.ramSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CpuFrequencyMhz {
            get {
                return this.cpuFrequencyMhzField;
            }
            set {
                this.cpuFrequencyMhzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NotOnBalance {
            get {
                return this.notOnBalanceField;
            }
            set {
                this.notOnBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool RequiresReplacement {
            get {
                return this.requiresReplacementField;
            }
            set {
                this.requiresReplacementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Appointment {
            get {
                return this.appointmentField;
            }
            set {
                this.appointmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VirtualizationEnvironment {
            get {
                return this.virtualizationEnvironmentField;
            }
            set {
                this.virtualizationEnvironmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FloorLocation {
            get {
                return this.floorLocationField;
            }
            set {
                this.floorLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoomLocation {
            get {
                return this.roomLocationField;
            }
            set {
                this.roomLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ActualOsVersion {
            get {
                return this.actualOsVersionField;
            }
            set {
                this.actualOsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OsActualVersion {
            get {
                return this.osActualVersionField;
            }
            set {
                this.osActualVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ZagsName {
            get {
                return this.zagsNameField;
            }
            set {
                this.zagsNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ZagsAddress {
            get {
                return this.zagsAddressField;
            }
            set {
                this.zagsAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeOfUse {
            get {
                return this.typeOfUseField;
            }
            set {
                this.typeOfUseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModelInDeliveryAccordance {
            get {
                return this.modelInDeliveryAccordanceField;
            }
            set {
                this.modelInDeliveryAccordanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransferContractNumber {
            get {
                return this.transferContractNumberField;
            }
            set {
                this.transferContractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PsVersion {
            get {
                return this.psVersionField;
            }
            set {
                this.psVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NetBiosName {
            get {
                return this.netBiosNameField;
            }
            set {
                this.netBiosNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AdditionalIPs {
            get {
                return this.additionalIPsField;
            }
            set {
                this.additionalIPsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CpuType {
            get {
                return this.cpuTypeField;
            }
            set {
                this.cpuTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RamType {
            get {
                return this.ramTypeField;
            }
            set {
                this.ramTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CdOrDvd {
            get {
                return this.cdOrDvdField;
            }
            set {
                this.cdOrDvdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fdd {
            get {
                return this.fddField;
            }
            set {
                this.fddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Raid {
            get {
                return this.raidField;
            }
            set {
                this.raidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HddType {
            get {
                return this.hddTypeField;
            }
            set {
                this.hddTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NetworkAdapter {
            get {
                return this.networkAdapterField;
            }
            set {
                this.networkAdapterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConnectedPcInventoryNumber {
            get {
                return this.connectedPcInventoryNumberField;
            }
            set {
                this.connectedPcInventoryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConnectedUpsInventoryNumber {
            get {
                return this.connectedUpsInventoryNumberField;
            }
            set {
                this.connectedUpsInventoryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayInventoryNumber {
            get {
                return this.displayInventoryNumberField;
            }
            set {
                this.displayInventoryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayServiceNumber {
            get {
                return this.displayServiceNumberField;
            }
            set {
                this.displayServiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayBrand {
            get {
                return this.displayBrandField;
            }
            set {
                this.displayBrandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayType {
            get {
                return this.displayTypeField;
            }
            set {
                this.displayTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplaySize {
            get {
                return this.displaySizeField;
            }
            set {
                this.displaySizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayMaxResolution {
            get {
                return this.displayMaxResolutionField;
            }
            set {
                this.displayMaxResolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeOfAnalogConnection {
            get {
                return this.typeOfAnalogConnectionField;
            }
            set {
                this.typeOfAnalogConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeOfDigitConnection {
            get {
                return this.typeOfDigitConnectionField;
            }
            set {
                this.typeOfDigitConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KeyNumber {
            get {
                return this.keyNumberField;
            }
            set {
                this.keyNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StreamerBrand {
            get {
                return this.streamerBrandField;
            }
            set {
                this.streamerBrandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StreamerCartridgeMark {
            get {
                return this.streamerCartridgeMarkField;
            }
            set {
                this.streamerCartridgeMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatingSystem {
            get {
                return this.operatingSystemField;
            }
            set {
                this.operatingSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServicePack {
            get {
                return this.servicePackField;
            }
            set {
                this.servicePackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OfficeSuite {
            get {
                return this.officeSuiteField;
            }
            set {
                this.officeSuiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fio {
            get {
                return this.fioField;
            }
            set {
                this.fioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResponsiblePerson {
            get {
                return this.responsiblePersonField;
            }
            set {
                this.responsiblePersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MacAddress {
            get {
                return this.macAddressField;
            }
            set {
                this.macAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string YearOfIssue {
            get {
                return this.yearOfIssueField;
            }
            set {
                this.yearOfIssueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComputerName {
            get {
                return this.computerNameField;
            }
            set {
                this.computerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventoryNumber {
            get {
                return this.inventoryNumberField;
            }
            set {
                this.inventoryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SupplyContract {
            get {
                return this.supplyContractField;
            }
            set {
                this.supplyContractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContractSto {
            get {
                return this.contractStoField;
            }
            set {
                this.contractStoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MailServer {
            get {
                return this.mailServerField;
            }
            set {
                this.mailServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirewallMailServer {
            get {
                return this.firewallMailServerField;
            }
            set {
                this.firewallMailServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirewallForVks {
            get {
                return this.firewallForVksField;
            }
            set {
                this.firewallForVksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AllModel {
        
        private EquipmentType equipmentTypeField;
        
        /// <remarks/>
        public EquipmentType EquipmentType {
            get {
                return this.equipmentTypeField;
            }
            set {
                this.equipmentTypeField = value;
            }
        }
    }
}
