//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 
namespace EfDatabase.ReportXml.XsdMail {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MailSheme {
        
        private MailInView[] mailInViewField;
        
        private MailOutView[] mailOutViewField;
        
        private WebMailModel webMailModelField;
        
        private CalendarVksStpView[] calendarVksStpViewField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MailInView")]
        public MailInView[] MailInView {
            get {
                return this.mailInViewField;
            }
            set {
                this.mailInViewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MailOutView")]
        public MailOutView[] MailOutView {
            get {
                return this.mailOutViewField;
            }
            set {
                this.mailOutViewField = value;
            }
        }
        
        /// <remarks/>
        public WebMailModel WebMailModel {
            get {
                return this.webMailModelField;
            }
            set {
                this.webMailModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CalendarVksStpView")]
        public CalendarVksStpView[] CalendarVksStpView {
            get {
                return this.calendarVksStpViewField;
            }
            set {
                this.calendarVksStpViewField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MailInView {
        
        private System.Nullable<System.DateTime> dateInputServerField;
        
        private int idField;
        
        private string idMailField;
        
        private string mailAdressSendField;
        
        private string mailAdressField;
        
        private string subjectMailField;
        
        private string isFileField;
        
        private string logicsButtonField;
        
        public MailInView() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateInputServer {
            get {
                return this.dateInputServerField;
            }
            set {
                this.dateInputServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdMail {
            get {
                return this.idMailField;
            }
            set {
                this.idMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MailAdressSend {
            get {
                return this.mailAdressSendField;
            }
            set {
                this.mailAdressSendField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MailAdress {
            get {
                return this.mailAdressField;
            }
            set {
                this.mailAdressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubjectMail {
            get {
                return this.subjectMailField;
            }
            set {
                this.subjectMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsFile {
            get {
                return this.isFileField;
            }
            set {
                this.isFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MailOutView {
        
        private System.Nullable<System.DateTime> dateCreateField;
        
        private int idField;
        
        private string idMailField;
        
        private string mailAdressInField;
        
        private string mailAdressOutField;
        
        private string subjectMailField;
        
        private string isFileField;
        
        private string errorMailField;
        
        private string logicsButtonField;
        
        public MailOutView() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateCreate {
            get {
                return this.dateCreateField;
            }
            set {
                this.dateCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdMail {
            get {
                return this.idMailField;
            }
            set {
                this.idMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MailAdressIn {
            get {
                return this.mailAdressInField;
            }
            set {
                this.mailAdressInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MailAdressOut {
            get {
                return this.mailAdressOutField;
            }
            set {
                this.mailAdressOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubjectMail {
            get {
                return this.subjectMailField;
            }
            set {
                this.subjectMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsFile {
            get {
                return this.isFileField;
            }
            set {
                this.isFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorMail {
            get {
                return this.errorMailField;
            }
            set {
                this.errorMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WebMailModel {
        
        private string idMailField;
        
        private string nameGroupModelField;
        
        /// <remarks/>
        public string IdMail {
            get {
                return this.idMailField;
            }
            set {
                this.idMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameGroupModel {
            get {
                return this.nameGroupModelField;
            }
            set {
                this.nameGroupModelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CalendarVksStpView {
        
        private System.Nullable<System.DateTime> dateStartField;
        
        private System.Nullable<System.DateTime> dateFinishField;
        
        private int idField;
        
        private string idMailField;
        
        private string descriptionVKSField;
        
        private string fullDescriptionField;
        
        private string idVKSField;
        
        private string isSTPField;
        
        private string logicsButtonField;
        
        public CalendarVksStpView() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateFinish {
            get {
                return this.dateFinishField;
            }
            set {
                this.dateFinishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdMail {
            get {
                return this.idMailField;
            }
            set {
                this.idMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DescriptionVKS {
            get {
                return this.descriptionVKSField;
            }
            set {
                this.descriptionVKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullDescription {
            get {
                return this.fullDescriptionField;
            }
            set {
                this.fullDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdVKS {
            get {
                return this.idVKSField;
            }
            set {
                this.idVKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsSTP {
            get {
                return this.isSTPField;
            }
            set {
                this.isSTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
    }
}
