//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2053.0.
// 
namespace EfDatabase.ReportXml.ModelFileServer {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FileServerSelectView {
        
        private AllFileServerSelect[] allFileServerSelectField;
        
        private DublicatteFileServerSelect[] dublicatteFileServerSelectField;
        
        private SizeMaxFileServerSelect[] sizeMaxFileServerSelectField;
        
        private ErrorFileServerSelect[] errorFileServerSelectField;
        
        private DspFileServer[] dspFileServerField;
        
        private DownloadFileServer downloadFileServerField;
        
        private ModelFileDetals modelFileDetalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllFileServerSelect")]
        public AllFileServerSelect[] AllFileServerSelect {
            get {
                return this.allFileServerSelectField;
            }
            set {
                this.allFileServerSelectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DublicatteFileServerSelect")]
        public DublicatteFileServerSelect[] DublicatteFileServerSelect {
            get {
                return this.dublicatteFileServerSelectField;
            }
            set {
                this.dublicatteFileServerSelectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SizeMaxFileServerSelect")]
        public SizeMaxFileServerSelect[] SizeMaxFileServerSelect {
            get {
                return this.sizeMaxFileServerSelectField;
            }
            set {
                this.sizeMaxFileServerSelectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorFileServerSelect")]
        public ErrorFileServerSelect[] ErrorFileServerSelect {
            get {
                return this.errorFileServerSelectField;
            }
            set {
                this.errorFileServerSelectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DspFileServer")]
        public DspFileServer[] DspFileServer {
            get {
                return this.dspFileServerField;
            }
            set {
                this.dspFileServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DownloadFileServer DownloadFileServer {
            get {
                return this.downloadFileServerField;
            }
            set {
                this.downloadFileServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ModelFileDetals ModelFileDetals {
            get {
                return this.modelFileDetalsField;
            }
            set {
                this.modelFileDetalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AllFileServerSelect {
        
        private string logicsButtonField;
        
        private int idFileField;
        
        private int idUserField;
        
        private string nameUserField;
        
        private string smallNameField;
        
        private string tabelNumberField;
        
        private string nameOtdelField;
        
        private string nameSaveField;
        
        private string fileOwnerAuthorField;
        
        private string lastAuthorField;
        
        private string fullPathFileField;
        
        private string pathFileField;
        
        private string nameFileField;
        
        private string itemTypeTextField;
        
        private string typeMimeField;
        
        private string fileExtensionField;
        
        private string sizeFileTextField;
        
        private long sizeFileField;
        
        private string hashFileField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateAccessedField;
        
        private System.DateTime dateModifiedField;
        
        private System.DateTime dateSavedField;
        
        public AllFileServerSelect() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdFile {
            get {
                return this.idFileField;
            }
            set {
                this.idFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameUser {
            get {
                return this.nameUserField;
            }
            set {
                this.nameUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SmallName {
            get {
                return this.smallNameField;
            }
            set {
                this.smallNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TabelNumber {
            get {
                return this.tabelNumberField;
            }
            set {
                this.tabelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOtdel {
            get {
                return this.nameOtdelField;
            }
            set {
                this.nameOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameSave {
            get {
                return this.nameSaveField;
            }
            set {
                this.nameSaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileOwnerAuthor {
            get {
                return this.fileOwnerAuthorField;
            }
            set {
                this.fileOwnerAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastAuthor {
            get {
                return this.lastAuthorField;
            }
            set {
                this.lastAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullPathFile {
            get {
                return this.fullPathFileField;
            }
            set {
                this.fullPathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PathFile {
            get {
                return this.pathFileField;
            }
            set {
                this.pathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemTypeText {
            get {
                return this.itemTypeTextField;
            }
            set {
                this.itemTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeMime {
            get {
                return this.typeMimeField;
            }
            set {
                this.typeMimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SizeFileText {
            get {
                return this.sizeFileTextField;
            }
            set {
                this.sizeFileTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long SizeFile {
            get {
                return this.sizeFileField;
            }
            set {
                this.sizeFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HashFile {
            get {
                return this.hashFileField;
            }
            set {
                this.hashFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateAccessed {
            get {
                return this.dateAccessedField;
            }
            set {
                this.dateAccessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateSaved {
            get {
                return this.dateSavedField;
            }
            set {
                this.dateSavedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DublicatteFileServerSelect {
        
        private string logicsButtonField;
        
        private int idFileField;
        
        private int idUserField;
        
        private string nameUserField;
        
        private string smallNameField;
        
        private string tabelNumberField;
        
        private string nameOtdelField;
        
        private string nameSaveField;
        
        private string fileOwnerAuthorField;
        
        private string lastAuthorField;
        
        private string fullPathFileField;
        
        private string pathFileField;
        
        private string nameFileField;
        
        private string itemTypeTextField;
        
        private string typeMimeField;
        
        private string fileExtensionField;
        
        private string sizeFileTextField;
        
        private long sizeFileField;
        
        private string hashFileField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateAccessedField;
        
        private System.DateTime dateModifiedField;
        
        private System.DateTime dateSavedField;
        
        public DublicatteFileServerSelect() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdFile {
            get {
                return this.idFileField;
            }
            set {
                this.idFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameUser {
            get {
                return this.nameUserField;
            }
            set {
                this.nameUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SmallName {
            get {
                return this.smallNameField;
            }
            set {
                this.smallNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TabelNumber {
            get {
                return this.tabelNumberField;
            }
            set {
                this.tabelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOtdel {
            get {
                return this.nameOtdelField;
            }
            set {
                this.nameOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameSave {
            get {
                return this.nameSaveField;
            }
            set {
                this.nameSaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileOwnerAuthor {
            get {
                return this.fileOwnerAuthorField;
            }
            set {
                this.fileOwnerAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastAuthor {
            get {
                return this.lastAuthorField;
            }
            set {
                this.lastAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullPathFile {
            get {
                return this.fullPathFileField;
            }
            set {
                this.fullPathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PathFile {
            get {
                return this.pathFileField;
            }
            set {
                this.pathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemTypeText {
            get {
                return this.itemTypeTextField;
            }
            set {
                this.itemTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeMime {
            get {
                return this.typeMimeField;
            }
            set {
                this.typeMimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SizeFileText {
            get {
                return this.sizeFileTextField;
            }
            set {
                this.sizeFileTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long SizeFile {
            get {
                return this.sizeFileField;
            }
            set {
                this.sizeFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HashFile {
            get {
                return this.hashFileField;
            }
            set {
                this.hashFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateAccessed {
            get {
                return this.dateAccessedField;
            }
            set {
                this.dateAccessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateSaved {
            get {
                return this.dateSavedField;
            }
            set {
                this.dateSavedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SizeMaxFileServerSelect {
        
        private string logicsButtonField;
        
        private int idFileField;
        
        private int idUserField;
        
        private string nameUserField;
        
        private string smallNameField;
        
        private string tabelNumberField;
        
        private string nameOtdelField;
        
        private string nameSaveField;
        
        private string fileOwnerAuthorField;
        
        private string lastAuthorField;
        
        private string fullPathFileField;
        
        private string pathFileField;
        
        private string nameFileField;
        
        private string itemTypeTextField;
        
        private string typeMimeField;
        
        private string fileExtensionField;
        
        private string sizeFileTextField;
        
        private long sizeFileField;
        
        private string hashFileField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateAccessedField;
        
        private System.DateTime dateModifiedField;
        
        private System.DateTime dateSavedField;
        
        public SizeMaxFileServerSelect() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdFile {
            get {
                return this.idFileField;
            }
            set {
                this.idFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameUser {
            get {
                return this.nameUserField;
            }
            set {
                this.nameUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SmallName {
            get {
                return this.smallNameField;
            }
            set {
                this.smallNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TabelNumber {
            get {
                return this.tabelNumberField;
            }
            set {
                this.tabelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOtdel {
            get {
                return this.nameOtdelField;
            }
            set {
                this.nameOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameSave {
            get {
                return this.nameSaveField;
            }
            set {
                this.nameSaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileOwnerAuthor {
            get {
                return this.fileOwnerAuthorField;
            }
            set {
                this.fileOwnerAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastAuthor {
            get {
                return this.lastAuthorField;
            }
            set {
                this.lastAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullPathFile {
            get {
                return this.fullPathFileField;
            }
            set {
                this.fullPathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PathFile {
            get {
                return this.pathFileField;
            }
            set {
                this.pathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemTypeText {
            get {
                return this.itemTypeTextField;
            }
            set {
                this.itemTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeMime {
            get {
                return this.typeMimeField;
            }
            set {
                this.typeMimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SizeFileText {
            get {
                return this.sizeFileTextField;
            }
            set {
                this.sizeFileTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long SizeFile {
            get {
                return this.sizeFileField;
            }
            set {
                this.sizeFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HashFile {
            get {
                return this.hashFileField;
            }
            set {
                this.hashFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateAccessed {
            get {
                return this.dateAccessedField;
            }
            set {
                this.dateAccessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateSaved {
            get {
                return this.dateSavedField;
            }
            set {
                this.dateSavedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ErrorFileServerSelect {
        
        private string logicsButtonField;
        
        private int idFileField;
        
        private string nameUserField;
        
        private string smallNameField;
        
        private string tabelNumberField;
        
        private string nameOtdelField;
        
        private string nameSaveField;
        
        private string fileOwnerAuthorField;
        
        private string lastAuthorField;
        
        private string fullPathFileField;
        
        private string pathFileField;
        
        private string nameFileField;
        
        private string itemTypeTextField;
        
        private string typeMimeField;
        
        private string fileExtensionField;
        
        private string sizeFileTextField;
        
        private long sizeFileField;
        
        private string hashFileField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateAccessedField;
        
        private System.DateTime dateModifiedField;
        
        private System.DateTime dateSavedField;
        
        private int idUserField;
        
        public ErrorFileServerSelect() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdFile {
            get {
                return this.idFileField;
            }
            set {
                this.idFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameUser {
            get {
                return this.nameUserField;
            }
            set {
                this.nameUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SmallName {
            get {
                return this.smallNameField;
            }
            set {
                this.smallNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TabelNumber {
            get {
                return this.tabelNumberField;
            }
            set {
                this.tabelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOtdel {
            get {
                return this.nameOtdelField;
            }
            set {
                this.nameOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameSave {
            get {
                return this.nameSaveField;
            }
            set {
                this.nameSaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileOwnerAuthor {
            get {
                return this.fileOwnerAuthorField;
            }
            set {
                this.fileOwnerAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastAuthor {
            get {
                return this.lastAuthorField;
            }
            set {
                this.lastAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullPathFile {
            get {
                return this.fullPathFileField;
            }
            set {
                this.fullPathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PathFile {
            get {
                return this.pathFileField;
            }
            set {
                this.pathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemTypeText {
            get {
                return this.itemTypeTextField;
            }
            set {
                this.itemTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeMime {
            get {
                return this.typeMimeField;
            }
            set {
                this.typeMimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SizeFileText {
            get {
                return this.sizeFileTextField;
            }
            set {
                this.sizeFileTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long SizeFile {
            get {
                return this.sizeFileField;
            }
            set {
                this.sizeFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HashFile {
            get {
                return this.hashFileField;
            }
            set {
                this.hashFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateAccessed {
            get {
                return this.dateAccessedField;
            }
            set {
                this.dateAccessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateSaved {
            get {
                return this.dateSavedField;
            }
            set {
                this.dateSavedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DspFileServer {
        
        private string logicsButtonField;
        
        private int idFileField;
        
        private int idUserField;
        
        private string nameUserField;
        
        private string smallNameField;
        
        private string tabelNumberField;
        
        private string nameOtdelField;
        
        private string nameSaveField;
        
        private string fileOwnerAuthorField;
        
        private string lastAuthorField;
        
        private string fullPathFileField;
        
        private string pathFileField;
        
        private string nameFileField;
        
        private string itemTypeTextField;
        
        private string typeMimeField;
        
        private string fileExtensionField;
        
        private string sizeFileTextField;
        
        private long sizeFileField;
        
        private string hashFileField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateAccessedField;
        
        private System.DateTime dateModifiedField;
        
        private System.DateTime dateSavedField;
        
        public DspFileServer() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdFile {
            get {
                return this.idFileField;
            }
            set {
                this.idFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameUser {
            get {
                return this.nameUserField;
            }
            set {
                this.nameUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SmallName {
            get {
                return this.smallNameField;
            }
            set {
                this.smallNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TabelNumber {
            get {
                return this.tabelNumberField;
            }
            set {
                this.tabelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOtdel {
            get {
                return this.nameOtdelField;
            }
            set {
                this.nameOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameSave {
            get {
                return this.nameSaveField;
            }
            set {
                this.nameSaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileOwnerAuthor {
            get {
                return this.fileOwnerAuthorField;
            }
            set {
                this.fileOwnerAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastAuthor {
            get {
                return this.lastAuthorField;
            }
            set {
                this.lastAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullPathFile {
            get {
                return this.fullPathFileField;
            }
            set {
                this.fullPathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PathFile {
            get {
                return this.pathFileField;
            }
            set {
                this.pathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemTypeText {
            get {
                return this.itemTypeTextField;
            }
            set {
                this.itemTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeMime {
            get {
                return this.typeMimeField;
            }
            set {
                this.typeMimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SizeFileText {
            get {
                return this.sizeFileTextField;
            }
            set {
                this.sizeFileTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long SizeFile {
            get {
                return this.sizeFileField;
            }
            set {
                this.sizeFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HashFile {
            get {
                return this.hashFileField;
            }
            set {
                this.hashFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateAccessed {
            get {
                return this.dateAccessedField;
            }
            set {
                this.dateAccessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateSaved {
            get {
                return this.dateSavedField;
            }
            set {
                this.dateSavedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class DownloadFileServer {
        
        private string fullPathFileField;
        
        private string nameFileField;
        
        private string itemTypeTextField;
        
        private string typeMimeField;
        
        private string fileExtensionField;
        
        private byte[] fileByteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullPathFile {
            get {
                return this.fullPathFileField;
            }
            set {
                this.fullPathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemTypeText {
            get {
                return this.itemTypeTextField;
            }
            set {
                this.itemTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeMime {
            get {
                return this.typeMimeField;
            }
            set {
                this.typeMimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] FileByte {
            get {
                return this.fileByteField;
            }
            set {
                this.fileByteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ModelFileDetals {
        
        private string[] allAutorFileField;
        
        private int idFileField;
        
        private int idUserField;
        
        private string nameUserField;
        
        private string smallNameField;
        
        private string tabelNumberField;
        
        private string nameOtdelField;
        
        private string nameSaveField;
        
        private string fileOwnerAuthorField;
        
        private string lastAuthorField;
        
        private string fullPathFileField;
        
        private string pathFileField;
        
        private string nameFileField;
        
        private string itemTypeTextField;
        
        private string typeMimeField;
        
        private string fileExtensionField;
        
        private string sizeFileTextField;
        
        private long sizeFileField;
        
        private string hashFileField;
        
        private string dateCreatedField;
        
        private string dateAccessedField;
        
        private string dateModifiedField;
        
        private string dateSavedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllAutorFile", IsNullable=true)]
        public string[] AllAutorFile {
            get {
                return this.allAutorFileField;
            }
            set {
                this.allAutorFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdFile {
            get {
                return this.idFileField;
            }
            set {
                this.idFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameUser {
            get {
                return this.nameUserField;
            }
            set {
                this.nameUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SmallName {
            get {
                return this.smallNameField;
            }
            set {
                this.smallNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TabelNumber {
            get {
                return this.tabelNumberField;
            }
            set {
                this.tabelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOtdel {
            get {
                return this.nameOtdelField;
            }
            set {
                this.nameOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameSave {
            get {
                return this.nameSaveField;
            }
            set {
                this.nameSaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileOwnerAuthor {
            get {
                return this.fileOwnerAuthorField;
            }
            set {
                this.fileOwnerAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastAuthor {
            get {
                return this.lastAuthorField;
            }
            set {
                this.lastAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullPathFile {
            get {
                return this.fullPathFileField;
            }
            set {
                this.fullPathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PathFile {
            get {
                return this.pathFileField;
            }
            set {
                this.pathFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemTypeText {
            get {
                return this.itemTypeTextField;
            }
            set {
                this.itemTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeMime {
            get {
                return this.typeMimeField;
            }
            set {
                this.typeMimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SizeFileText {
            get {
                return this.sizeFileTextField;
            }
            set {
                this.sizeFileTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long SizeFile {
            get {
                return this.sizeFileField;
            }
            set {
                this.sizeFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HashFile {
            get {
                return this.hashFileField;
            }
            set {
                this.hashFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DateAccessed {
            get {
                return this.dateAccessedField;
            }
            set {
                this.dateAccessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DateSaved {
            get {
                return this.dateSavedField;
            }
            set {
                this.dateSavedField = value;
            }
        }
    }
}
