//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIFNSTools.Detalizacia.WpfUserControl.Face.FL.File.SqlZaprosFile {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQLFILEFL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLFILEFL() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestIFNSTools.Detalizacia.WpfUserControl.Face.FL.File.SqlZaprosFile.SQLFILEFL", typeof(SQLFILEFL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select t2.архив,t2.имяфайлапр,t2.имяфайлавы from statistics t2 Join 2012\\Sved2012 t1 on t1.ID_FILE=t2.ID_FILE Where {0}.
        /// </summary>
        public static string FilePRFL2012andFileMI2012 {
            get {
                return ResourceManager.GetString("FilePRFL2012andFileMI2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select t2.архив,t2.имяфайлапр,t2.имяфайлавы from statistics t2 Join 2013\\Sved2013 t1 on t1.ID_FILE=t2.ID_FILE Where {0}.
        /// </summary>
        public static string FilePRFL2013andFileMI2013 {
            get {
                return ResourceManager.GetString("FilePRFL2013andFileMI2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select t2.архив,t2.имяфайлапр,t2.имяфайлавы from statistics t2 Join 2014\\Sved2014 t1 on t1.ID_FILE=t2.ID_FILE Where {0}.
        /// </summary>
        public static string FilePRFL2014andFileMI2014 {
            get {
                return ResourceManager.GetString("FilePRFL2014andFileMI2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select t2.архив,t2.имяфайлапр,t2.имяфайлавы from statistics t2 Join 2015\\Sved2015 t1 on t1.ID_FILE=t2.ID_FILE Where {0}.
        /// </summary>
        public static string FilePRFL2015andFileMI2015 {
            get {
                return ResourceManager.GetString("FilePRFL2015andFileMI2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select t2.архив,t2.имяфайлапр,t2.имяфайлавы from statistics t2 Join 2016\\Sved2016 t1 on t1.ID_FILE=t2.ID_FILE Where {0}.
        /// </summary>
        public static string FilePRFL2016andFileMI2016 {
            get {
                return ResourceManager.GetString("FilePRFL2016andFileMI2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select t2.архив,t2.имяфайлапр,t2.имяфайлавы from statistics t2 Join 2017\\Sved2017 t1 on t1.ID_FILE=t2.ID_FILE Where {0}.
        /// </summary>
        public static string FilePRFL2017andFileMI2017 {
            get {
                return ResourceManager.GetString("FilePRFL2017andFileMI2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select t2.архив,t2.имяфайлапр,t2.имяфайлавы from statistics t2 Join 2018\\Sved2018 t1 on t1.ID_FILE=t2.ID_FILE Where {0}.
        /// </summary>
        public static string FilePRFL2018andFileMI2018 {
            get {
                return ResourceManager.GetString("FilePRFL2018andFileMI2018", resourceCulture);
            }
        }
    }
}
