//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2053.0.
// 
namespace EfDatabaseParametrsModel {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AllTechnicalUsersAndOtdelAndTreeAis3 {
        
        private Users[] usersField;
        
        private Otdel[] otdelField;
        
        private AllTemplateAndTree[] allTemplateAndTreeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Users")]
        public Users[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Otdel")]
        public Otdel[] Otdel {
            get {
                return this.otdelField;
            }
            set {
                this.otdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllTemplateAndTree")]
        public AllTemplateAndTree[] AllTemplateAndTree {
            get {
                return this.allTemplateAndTreeField;
            }
            set {
                this.allTemplateAndTreeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Users {
        
        private Monitors[] monitorsField;
        
        private Mfu[] mfuField;
        
        private Printer[] printerField;
        
        private ScanerAndCamer[] scanerAndCamerField;
        
        private SysBlock[] sysBlockField;
        
        private BlockPower[] blockPowerField;
        
        private Telephon telephonField;
        
        private Swithe[] switheField;
        
        private Token[] tokenField;
        
        private OtherAll[] otherAllField;
        
        private int idUserField;
        
        private bool idUserFieldSpecified;
        
        private string nameUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Monitors")]
        public Monitors[] Monitors {
            get {
                return this.monitorsField;
            }
            set {
                this.monitorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mfu")]
        public Mfu[] Mfu {
            get {
                return this.mfuField;
            }
            set {
                this.mfuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Printer")]
        public Printer[] Printer {
            get {
                return this.printerField;
            }
            set {
                this.printerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScanerAndCamer")]
        public ScanerAndCamer[] ScanerAndCamer {
            get {
                return this.scanerAndCamerField;
            }
            set {
                this.scanerAndCamerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SysBlock")]
        public SysBlock[] SysBlock {
            get {
                return this.sysBlockField;
            }
            set {
                this.sysBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BlockPower")]
        public BlockPower[] BlockPower {
            get {
                return this.blockPowerField;
            }
            set {
                this.blockPowerField = value;
            }
        }
        
        /// <remarks/>
        public Telephon Telephon {
            get {
                return this.telephonField;
            }
            set {
                this.telephonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Swithe")]
        public Swithe[] Swithe {
            get {
                return this.switheField;
            }
            set {
                this.switheField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public Token[] Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherAll")]
        public OtherAll[] OtherAll {
            get {
                return this.otherAllField;
            }
            set {
                this.otherAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUserSpecified {
            get {
                return this.idUserFieldSpecified;
            }
            set {
                this.idUserFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameUser {
            get {
                return this.nameUserField;
            }
            set {
                this.nameUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Monitors {
        
        private Kabinet kabinetField;
        
        private NameMonitor nameMonitorField;
        
        private string serNumField;
        
        private string inventarNumMonitorField;
        
        private string comentField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        public NameMonitor NameMonitor {
            get {
                return this.nameMonitorField;
            }
            set {
                this.nameMonitorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerNum {
            get {
                return this.serNumField;
            }
            set {
                this.serNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventarNumMonitor {
            get {
                return this.inventarNumMonitorField;
            }
            set {
                this.inventarNumMonitorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coment {
            get {
                return this.comentField;
            }
            set {
                this.comentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Kabinet {
        
        private string numberKabinetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumberKabinet {
            get {
                return this.numberKabinetField;
            }
            set {
                this.numberKabinetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NameMonitor {
        
        private string nameManufacturerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameManufacturer {
            get {
                return this.nameManufacturerField;
            }
            set {
                this.nameManufacturerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Mfu {
        
        private Kabinet kabinetField;
        
        private CopySave copySaveField;
        
        private FullProizvoditel fullProizvoditelField;
        
        private FullModel fullModelField;
        
        private string zavNumberField;
        
        private string serviceNumberField;
        
        private string comentField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        public CopySave CopySave {
            get {
                return this.copySaveField;
            }
            set {
                this.copySaveField = value;
            }
        }
        
        /// <remarks/>
        public FullProizvoditel FullProizvoditel {
            get {
                return this.fullProizvoditelField;
            }
            set {
                this.fullProizvoditelField = value;
            }
        }
        
        /// <remarks/>
        public FullModel FullModel {
            get {
                return this.fullModelField;
            }
            set {
                this.fullModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ZavNumber {
            get {
                return this.zavNumberField;
            }
            set {
                this.zavNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coment {
            get {
                return this.comentField;
            }
            set {
                this.comentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CopySave {
        
        private string nameCopySaveField;
        
        private string serNumCopySaveField;
        
        private string inventarNumCopySaveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameCopySave {
            get {
                return this.nameCopySaveField;
            }
            set {
                this.nameCopySaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerNumCopySave {
            get {
                return this.serNumCopySaveField;
            }
            set {
                this.serNumCopySaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventarNumCopySave {
            get {
                return this.inventarNumCopySaveField;
            }
            set {
                this.inventarNumCopySaveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FullProizvoditel {
        
        private string nameProizvoditelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameProizvoditel {
            get {
                return this.nameProizvoditelField;
            }
            set {
                this.nameProizvoditelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FullModel {
        
        private string nameModelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameModel {
            get {
                return this.nameModelField;
            }
            set {
                this.nameModelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Printer {
        
        private Kabinet kabinetField;
        
        private FullProizvoditel fullProizvoditelField;
        
        private FullModel fullModelField;
        
        private string zavNumberField;
        
        private string serviceNumberField;
        
        private string comentField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        public FullProizvoditel FullProizvoditel {
            get {
                return this.fullProizvoditelField;
            }
            set {
                this.fullProizvoditelField = value;
            }
        }
        
        /// <remarks/>
        public FullModel FullModel {
            get {
                return this.fullModelField;
            }
            set {
                this.fullModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ZavNumber {
            get {
                return this.zavNumberField;
            }
            set {
                this.zavNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coment {
            get {
                return this.comentField;
            }
            set {
                this.comentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ScanerAndCamer {
        
        private Kabinet kabinetField;
        
        private FullProizvoditel fullProizvoditelField;
        
        private FullModel fullModelField;
        
        private string zavNumberField;
        
        private string serviceNumberField;
        
        private string inventarNumberField;
        
        private string comentField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        public FullProizvoditel FullProizvoditel {
            get {
                return this.fullProizvoditelField;
            }
            set {
                this.fullProizvoditelField = value;
            }
        }
        
        /// <remarks/>
        public FullModel FullModel {
            get {
                return this.fullModelField;
            }
            set {
                this.fullModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ZavNumber {
            get {
                return this.zavNumberField;
            }
            set {
                this.zavNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventarNumber {
            get {
                return this.inventarNumberField;
            }
            set {
                this.inventarNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coment {
            get {
                return this.comentField;
            }
            set {
                this.comentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SysBlock {
        
        private Kabinet kabinetField;
        
        private NameSysBlock nameSysBlockField;
        
        private string serviceNumField;
        
        private string serNumField;
        
        private string inventarNumSysBlokField;
        
        private string nameComputerField;
        
        private string ipAdressField;
        
        private string comentField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        public NameSysBlock NameSysBlock {
            get {
                return this.nameSysBlockField;
            }
            set {
                this.nameSysBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNum {
            get {
                return this.serviceNumField;
            }
            set {
                this.serviceNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerNum {
            get {
                return this.serNumField;
            }
            set {
                this.serNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventarNumSysBlok {
            get {
                return this.inventarNumSysBlokField;
            }
            set {
                this.inventarNumSysBlokField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameComputer {
            get {
                return this.nameComputerField;
            }
            set {
                this.nameComputerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IpAdress {
            get {
                return this.ipAdressField;
            }
            set {
                this.ipAdressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coment {
            get {
                return this.comentField;
            }
            set {
                this.comentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NameSysBlock {
        
        private string nameComputerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameComputer {
            get {
                return this.nameComputerField;
            }
            set {
                this.nameComputerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BlockPower {
        
        private Kabinet kabinetField;
        
        private ProizvoditelBlockPower proizvoditelBlockPowerField;
        
        private ModelBlockPower modelBlockPowerField;
        
        private string zavNumberField;
        
        private string inventarNumberField;
        
        private string serviceNumberField;
        
        private string comentField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        public ProizvoditelBlockPower ProizvoditelBlockPower {
            get {
                return this.proizvoditelBlockPowerField;
            }
            set {
                this.proizvoditelBlockPowerField = value;
            }
        }
        
        /// <remarks/>
        public ModelBlockPower ModelBlockPower {
            get {
                return this.modelBlockPowerField;
            }
            set {
                this.modelBlockPowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ZavNumber {
            get {
                return this.zavNumberField;
            }
            set {
                this.zavNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventarNumber {
            get {
                return this.inventarNumberField;
            }
            set {
                this.inventarNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coment {
            get {
                return this.comentField;
            }
            set {
                this.comentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ProizvoditelBlockPower {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelBlockPower {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Telephon {
        
        private Kabinet kabinetField;
        
        private ModelPhone modelPhoneField;
        
        private string serNumberField;
        
        private string ipTelephonField;
        
        private string macTelephonField;
        
        private string comentField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        public ModelPhone ModelPhone {
            get {
                return this.modelPhoneField;
            }
            set {
                this.modelPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerNumber {
            get {
                return this.serNumberField;
            }
            set {
                this.serNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IpTelephon {
            get {
                return this.ipTelephonField;
            }
            set {
                this.ipTelephonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MacTelephon {
            get {
                return this.macTelephonField;
            }
            set {
                this.macTelephonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coment {
            get {
                return this.comentField;
            }
            set {
                this.comentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelPhone {
        
        private string nameModelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameModel {
            get {
                return this.nameModelField;
            }
            set {
                this.nameModelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Swithe {
        
        private Kabinet kabinetField;
        
        private ModelSwithe modelSwitheField;
        
        private string serviceNumField;
        
        private string serNumField;
        
        private string inventarNumField;
        
        private string comentField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        public ModelSwithe ModelSwithe {
            get {
                return this.modelSwitheField;
            }
            set {
                this.modelSwitheField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNum {
            get {
                return this.serviceNumField;
            }
            set {
                this.serviceNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerNum {
            get {
                return this.serNumField;
            }
            set {
                this.serNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventarNum {
            get {
                return this.inventarNumField;
            }
            set {
                this.inventarNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coment {
            get {
                return this.comentField;
            }
            set {
                this.comentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelSwithe {
        
        private string nameModelField;
        
        private string countPortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameModel {
            get {
                return this.nameModelField;
            }
            set {
                this.nameModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountPort {
            get {
                return this.countPortField;
            }
            set {
                this.countPortField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Token {
        
        private Kabinet kabinetField;
        
        private string serviceNumField;
        
        private string serNumField;
        
        private string inventarNumField;
        
        private string proizvoditelNameField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNum {
            get {
                return this.serviceNumField;
            }
            set {
                this.serviceNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerNum {
            get {
                return this.serNumField;
            }
            set {
                this.serNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventarNum {
            get {
                return this.inventarNumField;
            }
            set {
                this.inventarNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProizvoditelName {
            get {
                return this.proizvoditelNameField;
            }
            set {
                this.proizvoditelNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OtherAll {
        
        private Kabinet kabinetField;
        
        private ProizvoditelOther proizvoditelOtherField;
        
        private ModelOther modelOtherField;
        
        private string serviceNumberField;
        
        private string serNumField;
        
        private string inventarNumField;
        
        private string comentField;
        
        /// <remarks/>
        public Kabinet Kabinet {
            get {
                return this.kabinetField;
            }
            set {
                this.kabinetField = value;
            }
        }
        
        /// <remarks/>
        public ProizvoditelOther ProizvoditelOther {
            get {
                return this.proizvoditelOtherField;
            }
            set {
                this.proizvoditelOtherField = value;
            }
        }
        
        /// <remarks/>
        public ModelOther ModelOther {
            get {
                return this.modelOtherField;
            }
            set {
                this.modelOtherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerNum {
            get {
                return this.serNumField;
            }
            set {
                this.serNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InventarNum {
            get {
                return this.inventarNumField;
            }
            set {
                this.inventarNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coment {
            get {
                return this.comentField;
            }
            set {
                this.comentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ProizvoditelOther {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelOther {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Otdel {
        
        private Users[] usersField;
        
        private string nameOtdelField;
        
        private string idUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Users")]
        public Users[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOtdel {
            get {
                return this.nameOtdelField;
            }
            set {
                this.nameOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AllTemplateAndTree {
        
        private TableTemplate tableTemplateField;
        
        /// <remarks/>
        public TableTemplate TableTemplate {
            get {
                return this.tableTemplateField;
            }
            set {
                this.tableTemplateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TableTemplate {
        
        private TableTasks[] tableTasksField;
        
        private string namesField;
        
        private string categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TableTasks")]
        public TableTasks[] TableTasks {
            get {
                return this.tableTasksField;
            }
            set {
                this.tableTasksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Names {
            get {
                return this.namesField;
            }
            set {
                this.namesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TableTasks {
        
        private string pathField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
}
