//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2053.0.
// 
namespace EfDatabase.XsdInventoryRuleAndUsers {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RuleAllAndUsers {
        
        private RuleUsers[] ruleUsersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RuleUsers")]
        public RuleUsers[] RuleUsers {
            get {
                return this.ruleUsersField;
            }
            set {
                this.ruleUsersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RuleUsers {
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private System.Nullable<int> idUserField;
        
        private bool idUserFieldSpecified;
        
        private int idRuleField;
        
        private string nameRulesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUserSpecified {
            get {
                return this.idUserFieldSpecified;
            }
            set {
                this.idUserFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdRule {
            get {
                return this.idRuleField;
            }
            set {
                this.idRuleField = value;
            }
        }
        
        /// <remarks/>
        public string NameRules {
            get {
                return this.nameRulesField;
            }
            set {
                this.nameRulesField = value;
            }
        }
    }
}
